micronaut:
  application:
    name: wge

  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:static/wge/browser

datasources:
  default:
    password: ${JDBC_PASSWORD:""}
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    driver-class-name: ${JDBC_DRIVER:org.h2.Driver}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
          show_sql: true

liquibase:
  datasources:
    default:
      enabled: true
      change-log: 'classpath:db/liquibase-changelog.xml'